<?php
/***********************
 *
 * Problem 2 from Project Euler
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms
 * will be:
 *  
 *  1,2,3,5,8,12,21,34,55,89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
 *
 * PLEASE NOTE
 * In order to work you must have, at least, PHP 5.3.x or Higher
 *
 * REGARDING THE PERFORMANCE
 * This is not the final version of the script, you can improve the algorithm by submitting a pull request or an issue on Github.
 * Feel free to ask for anything on Github.
 *
 * @author Santo Antonio Terranova (@tng46)
 * @version 2.0.0
 **************************/
   
       $startTest = microtime();

    $a = 1;
    $b = 2;
    $l = 4e6;
    $c = 2;
    $c3 = 0;
    $sum = 0;
    while ($a<$l) {
        $sum += $c3;

        $c2 = $a + 2*$b;
        $c3 = 2*$a + 3*$b;

        $a = $c2;
        $b = $c3;

    } 
    $result = 2 + $sum;

 
    $endTest = microtime();
    echo "Test time: ". ($endTest - $startTest). "\n";
